predicates = [
  "treat", "treats", "treated", "treated by",
   "caused by", "cause", "causes", "caused",
  "prevent", "prevents", "prevented", "prevented by",
  "predispose", "predisposes", "predisposed", "predisposed by",
  "encourage", "encourages", "encouraged", "encouraged by",
  "discourage", "discourages", "discouraged", "discouraged by",
  "catalyze", "catalyzes", "catalyzed", "catalyzed by",
  "conjugate", "conjugates", "conjugated", "conjugated by",
  "connect", "connects to", "connects with", "connects", "connected", "connected with", "connected by",
  "considered as",
  "consume", "consumes", "consumed", "consumed by",
  "create", "creates", "created", "created by",
  "acetylate", "acetylates", "acetylated", "acetylated by",
  "deacetylate", "deacetylates", "deacetylated", "deacetylated by",
  "absorb", "absorbs", "absorbed", "absorbed by",
  "accelerate", "accelerates", "accelerated", "accelerated by",
  "decelerate", "decelerates", "decelerated", "decelerated by",
  "accumulate", "accumulates", "accumulated", "accumulated by",
  "act as", "acts as", "acted as",
  "activate", "activates", "activated", "activated by",
  "deactivate", "deactivates", "deactivated", "deactivated by",
  "adapt", "adapts", "adapted", "adapted by",
  "add", "adds", "added", "added by",
  "affect", "affects", "affected", "affected by",
  "aggregate", "aggregates", "aggregated", "aggregated by",
  "believe", "believes", "believed",
  "associate", "associates", "associated", "associated with"
]
